prjGAS/gasbravo/urls.py
from os import name
from django.urls import path
from . import views


urlpatterns = [
    #Views Login Crear Usuarios 
    path('', views.index),
    path('user/create_user', views.create_user),
    path('user/login', views.login),
    path('logout', views.logout),
    path('user/logout', views.logout),
    path('user/dashboard',views.dashboard_rol),
    #Views Direcciones
    path('user/gest_direccion',views.gest_direccion),
    path('user/add_direccion',views.createAddress),
    path('user_dir/<int:number>/edit', views.edit_dir),
    path('user_dir/update/<int:number>',views.edit_dir),
    path('user_dir/<int:number>/delete',views.delete_dir),
    #Views Usuarios
    path('user/create_users', views.create_users),
    path('user/gestion_users',views.gest_users),
    path('user_usr/<int:number>/edit', views.edit_usr),
    path('user_usr/update/<int:number>',views. edit_usr),
    path('user_cli/<int:number>/edit', views.edit_usr_cl),
    path('user_cli/update/<int:number>',views. edit_usr_cl),
    path('user/<int:number>/delete',views.delete_user),
    #Views Productos    
    path('user/create_prod', views.create_prod),
    path('user/gestion_prod',views.gest_prod),
    path('user_prd/<int:number>/edit', views.edit_prd),
    path('user_prd/update/<int:number>',views. edit_prd),
    path('user_prod/<int:number>/delete',views.delete_prod),

    #Views Bodegas
    path('user/create_bodega', views.create_bod),
    path('user/gestion_bodega',views.gest_bod),
    path('user_bod/<int:number>/delete',views.delete_bod),
    
    #test
    path('user/test', views.test),
    # Pedidos
    path('user/create_pedido', views.crear_pedido),
    path('user/procesar_pedido', views.procesar_pedido),
    path('user/cancelar_pedido/<int:id_pedido>', views.cancelar_pedido),
    path('user/pedidos',  views.mostrar_pedidos),
    path('user/gestion_pedidos',  views.gestion_pedidos),
    path('user/despachar_pedido/<int:pedido_id>',  views.despachar_pedido),
    path('user/entregar_pedido/<int:pedido_id>',  views.enviar_pedido),
    path('user/pedido_detalle/<int:pedido_id>',  views.detalle_pedido),

    #sending email
    path('user/sending', views.sendmesa),

    #creating pdf
    path('user/invoice/<int:pedido_id>', views.invoice_pdf_view),

]

prjGAS/prjGAS/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gasbravo.urls')),
]

prjGAS/gasbravo/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.fields import DateField, IntegerField
from datetime import date
import re
# Create your models here.

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9.+_-]+\.[a-zA-Z]+$')
NAME_REGEX = re.compile(r'[0-9]')
NUM_REGEX = re.compile(r'[a-zA-Z]')

class UserManager(models.Manager):
    def registration_validator(self, postData):
        # ALL THE VALIDATION FOR THE FORM
        errors = {}
        if len(postData['first_name']) < 1 :
            errors['first_name'] = "Nombre no valido debe tener al menos 2 caracteres."
        if len(postData['last_name']) < 1:
            errors['last_name'] = "Apellido no valido. debe tener al menos 2 caracteres"
        if NAME_REGEX.search(postData['first_name']):
            errors["fist_name"] = "First name cannot contain any numbers"
        if NAME_REGEX.search(postData['last_name']):
            errors["last_name"] = "Last name cannot contain any numbers"
        if not EMAIL_REGEX.match(postData['email']):   
            errors['email'] = "Invalid email address!"
        users_with_email = User.objects.filter(email = postData['email'])
        if len(users_with_email) >= 1:
            errors['duplicate'] = "Email already exists."
        if len(postData['password']) < 7:
            errors['password'] = "El Password debe tener al menos 8 caracteres"
        if postData['password'] != postData['confirm_password']:
            errors['pw_match'] = "Password must match!"
        return errors 

class DireccionManager(models.Manager):
    def direccion_validator(self,postData):
        errors = {}
        if len(postData['nomdirec']) < 2:
            errors['nomdirec'] = "El nombre de la direción debe tener mas de 3 caracteres"
        if len(postData['celular']) > 10:
            errors['celular'] = "El número de teléfono no debe superar 10 digitos"
        if NUM_REGEX.search(postData['celular']):
            errors["last_name"] = "No se admiten letras en en celular"        
        if len(postData['desc']) < 5:
            errors['desc'] = "La descripción debe tener mas de 5 caracteres"
        return errors

class ProductoManager(models.Manager):
    def prod_validator(self,postData):
        errors = {}
        if len(postData['nombre_prod']) < 2:
            errors['nombre_prod'] = "El nombre del producto debe tener mas de 2 caracteres"
        if len(postData['peso']) < 1:
            errors['peso'] = "El peso del cilindro debe tener mas de 1 caracter"
        if len(postData['tipo']) < 4:
            errors['tipo'] = "El tipo del cilindro debe tener mas de 5 caracteres"
        if len(postData['color']) < 2:
            errors['color'] = "El color del cilindro debe tener mas de 2 caracteres"

        return errors
    
class BodegaManager(models.Manager):
    def bod_validator(self,postData):
        errors = {}
        current_date = date.today()
        if len(postData['cantidad']) < 1:
            errors['cantidad'] = "La cantidad ingresada debe ser mayor que 0"
        if len(postData['factura']) < 1:
            errors['factura'] = "La factura debe tener 15 caracteres"
        if len(postData['precio_compra']) == 0:
            errors['precio_compra'] = "El precio de compra no puede ser 0"
        if postData['fecha_ingr'] > current_date.strftime("%Y-%m-%d"):
            errors['fecha_ingr'] = "La fecha de ingreso no puede ser mayor a la fecha actual"
        return errors

class PedidoManager(models.Manager):
    def pedvalidator(self,postData):
        errors = {}
        if len(postData['dire_id']) == 0:
            errors['dire_id'] = "Debe tener una direccion primero"
        return errors

class Ped_ProdManager(models.Manager):
    def ped_prod_validator(self,postData):
        errors = {}
        if len(postData['cantidad']) < 1:
            errors['cantidad'] = "La cantidad ingresada debe ser mayor que 0"
        return errors

class Rol (models.Model):
    ROLES = (
        ('Cliente', 'Cliente'),
        ('Admin', 'Admin'),
    )
    roles = models.CharField(max_length=50, choices = ROLES, null=True)

class User (models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=55)
    email = models.CharField(max_length=55)
    password = models.CharField(max_length=55)
    user_rol = models.ForeignKey(Rol, related_name="user_rol", on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    objects = UserManager()

class Direccion (models.Model):
    nombre_dir = models.CharField(max_length=50)
    user_log = models.ForeignKey(User, related_name="user_log", on_delete=models.CASCADE)
    lat = models.CharField(max_length=50)
    long = models.CharField(max_length=50)
    celular =models.CharField(max_length=10)
    desc = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    objects = DireccionManager()

class Producto (models.Model):
    nombre_prod = models.CharField(max_length=30)
    peso = models.CharField(max_length=2)
    tipo = models.CharField(max_length=25)
    color = models.CharField(max_length=25, null=True)
    precio_venta = models.DecimalField(
        max_digits=5, decimal_places=2, default=0.00, null=True)
    cantidad_stock = models.IntegerField(default=0)
    estado = models.BooleanField(default=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    objects = ProductoManager()

class Bodega (models.Model):
    prod_bod = models.ForeignKey(Producto, related_name="prod_bod", on_delete=models.CASCADE)
    factura = models.CharField(max_length=15)
    fecha_ingr = models.DateField(null=True)
    cantidad = models.IntegerField(default=0)
    precio_compra = models.DecimalField(max_digits=5, decimal_places=2, default=0.00, null=True)
    proveedor = models.CharField(max_length=250, null= True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    objects = BodegaManager()

class Status_Ped (models.Model):
    ESTADOS = (
        ('Pendiente', 'Pendiente'),
        ('Despachado', 'Despachado'),
        ('Entregado', 'Entregado'),
        ('Cancelado', 'Cancelado'),
    )
    estados = models.CharField(max_length=50, choices=ESTADOS, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)


class Pedido (models.Model):
    cliente = models.CharField(max_length=250, default="Consumidor Final")
    cedula = models.CharField(max_length=15, default='9999999999')
    correo = models.CharField(max_length= 250, default='facturaciongas@gmail.com')
    dire_id = models.ForeignKey(Direccion, related_name="dire_id", on_delete=models.CASCADE)
    stat_id = models.ForeignKey(Status_Ped, related_name="stat_id", on_delete=models.CASCADE)
    usr_id = models.ForeignKey(User, related_name="usr_id", on_delete=models.CASCADE)
    
    subtotal_pedido = models.DecimalField(
        max_digits=5, decimal_places=2, default=0.00, null=True)
    iva_pedido = models.DecimalField(
        max_digits=5, decimal_places=2, default=0.00, null=True)
    total_pedido = models.DecimalField(
        max_digits=5, decimal_places=2, default=0.00, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True) 
    objects =  PedidoManager() 

class Pedido_prod (models.Model):
    ped_id = models.ForeignKey(Pedido,related_name="ped_id", on_delete=models.CASCADE)
    prod_id = models.ForeignKey(Producto,related_name="prod_id", on_delete=models.CASCADE)  
    cantidad = models.IntegerField()
    precio =  models.DecimalField(
        max_digits=5, decimal_places=2, default=0.00, null=True)
    costo = models.DecimalField(
        max_digits=5, decimal_places=2, default=0.00, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    objects =  Ped_ProdManager() 

prjGAS/gasbravo/templates/creardir_us.html
{% extends 'layouts/base-cl.html' %} {% block title %} Gestión Dirección {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div class="container-fluid">
    <div class="page-header min-height-150 border-radius-xl mt-4" style="background-image: url('/static/assets/img/curved-images/curved14.jpg'); background-position-y: 15%;">
        <span class="mask bg-gradient-info opacity-5"></span>
    </div>
    <div class="card card-body blur shadow-blur mx-4 mt-n6">
        <div class="row gx-4">
            <div class="col-auto">
                <div class="avatar avatar-xl position-relative">

                    <img src="/static/assets/img/usuario5.png" alt="avatar.png" class="w-100 border-radius-lg shadow-sm">


                </div>
            </div>
            <div class="col-auto my-auto">
                <div class="h-100">
                    <h5 class="mb-1">
                        {{logged_user.first_name}} {{logged_user.last_name}}
                    </h5>
                    <p class="mb-0 font-weight-bold text-sm">
                        {{logged_user.email}}
                    </p>
                </div>
            </div>

        </div>
    </div>
</div>
<!-- sección 2 cards -->
<div class="container-fluid py-4">
    <div class="row my-4">

        <!-- card izquierda -->
        <div class="col-lg-4 col-md-6 mb-md-0">
            <div class="card mb-2">
                <div class="card-header pb-0 p-3">
                    <h6 class="mb-1">Registro dirección</h6>

                </div>
                <div class=" col-md-12 d-flex flex-column">
                    <div class="card card-plain mt-1">
                        <div class="card-header pb-0 text-left bg-transparent">

                            {% if messages %}
                            <ul class="messages">
                                {% for message in messages%}
                                <li class="text-danger"><strong class="text-danger text-capitalize">{{message.tags}}:</strong> {{message}} {% endfor %}</li>
                            </ul>
                            {% else %} Por favor ingrese nueva dirección{% endif %}
                            </p>
                        </div>

                        <div class="card-body">
                            <form role="form text-left" method="post" action="/user/add_direccion">

                                {% csrf_token %}

                                <label for="nomdirec" class="form-label">Dirección</label>
                                <div class="mb-2">
                                    <input type="text" class="form-control" name="nomdirec" placeholder="Ingrese dirección completa" required>
                                </div>
                                <label for="celular" class="form-label">Teléfono</label>
                                <div class="mb-2">
                                    <input type="number" class="form-control" name="celular" placeholder="Ingrese número de teléfono" required>
                                </div>
                                <label for="desc" class="form-label">Referencia</label>
                                <div class="mb-2">
                                    <textarea class="form-control" name="desc" placeholder="Ingrese referencia" required></textarea>
                                </div>

                                <label for="id_lat" class="form-label">Latitud</label>
                                <div class="mb-2">
                                    <input type="text" class="form-control" name="id_lat" id="id_lat" placeholder="Ingrese coordenadas latitud" readonly>
                                </div>
                                <label for="id_lng" class="form-label">Longitud</label>
                                <div class="mb-2">
                                    <input type="text" class="form-control" name="id_lng" id="id_lng" placeholder="Ingrese coordenadas longitud" readonly>
                                </div>

                                <div class="mb-3 row g-2 text-center">
                                    <div class="col-md">
                                        <button type="submit" name="save" class="btn bg-gradient-info mt-4 mb-0">Guardar</button>
                                    </div>
                                    <div class="col-md">
                                        <a href="/user/dashboard">
                                            <button type="button" class="btn bg-gradient-primary  mt-4 mb-0">Cancelar</button>
                                        </a>

                                    </div>
                                </div>

                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- card derecha -->
        <div class="col-lg-8 col-md-6">
            <div class="card mb-2">
                <div class="card-header pb-0 p-3">

                    <div class="col-lg-6 col-7">
                        <h6>Ubicación Mapa</h6>
                        <span> Si no Carga Google Maps clic </span>
                        <a title="Reload!" href="/user/gest_direccion" onclick="window.location.reload(true)">Aqui !</a>

                        <div id="mapa" class="capas "></div>
                        <script src="https://maps.googleapis.com/maps/api/js?key={{google_api_key}}&callback=initMap&libraries=&v=weekly" async></script>
                        <script src="/static/assets/js/google.js"></script>
                    </div>


                </div>
                <div class="card-body px-0 pb-2">

                </div>
            </div>
            <div class="card mb-2">
                <div class="card-header pb-0 p-3">
                    <div class="row">
                        <div class="col-lg-6 col-7">
                            <h6>Direcciones Registradas</h6>

                        </div>
                        <div class="col-lg-6 col-5 my-auto text-end">

                        </div>
                    </div>
                </div>
                <div class="card-body px-0 pb-2">
                    <div class="table-responsive">
                        <table class="table align-items-center mb-0">
                            <thead>
                                <tr>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Dirección</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Teléfono</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Descripción</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Latitud</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Longitud</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Acción</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for dir in user_dir%}
                                <tr>
                                    <td class="align-middle text-center text-xxs">

                                        <span class="text-xxs">{{dir.nombre_dir}}</span>
                                    </td>
                                    <td class="align-middle text-center text-sm">
                                        <span class="text-xxs">{{dir.celular}}</span>
                                    </td>
                                    <td class="align-middle text-center text-sm">
                                        <span class="text-xxs"> {{dir.desc}} </span>
                                    </td>
                                    <td class="align-middle text-center text-sm">
                                        <span class="text-xxs">{{dir.lat}} </span>
                                    </td>
                                    <td class="align-middle text-center text-sm">
                                        <span class="text-xxs ">{{dir.long}}</span>
                                    </td>


                                    <td class="align-left text-center text-xxs">
                                        <div class="ms-auto">

                                            <a class="btn btn-link text-warning text-xxs  text-gradient px-1 mb-0" href="/user_dir/{{dir.id}}/edit"><i class="far fa-edit me-2"></i>Editar</a>
                                            <a class="btn btn-link text-danger text-xxs  text-gradient px-1 mb-0" href="/user_dir/{{dir.id}}/delete"><i class="far fa-trash-alt me-2"></i>Eliminar</a>
                                        </div>
                                    </td>

                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>


{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script src="https://maps.googleapis.com/maps/api/js?key={{google_api_key}}&callback=initMap&libraries=&v=weekly" async></script>
<script src="/static/assets/js/google.js"></script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>

{% endblock javascripts %}

prjGAS/gasbravo/templates/edit_dir.html
{% extends 'layouts/base-cl.html' %} {% block title %} Modificar Dirección {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div class="container-fluid">
    <div class="page-header min-height-150 border-radius-xl mt-4" style="background-image: url('/static/assets/img/curved-images/curved14.jpg'); background-position-y: 15%;">
        <span class="mask bg-gradient-info opacity-5"></span>
    </div>
    <div class="card card-body blur shadow-blur mx-4 mt-n6">
        <div class="row gx-4">
            <div class="col-auto">
                <div class="avatar avatar-xl position-relative">

                    <img src="/static/assets/img/usuario5.png" alt="avatar.png" class="w-100 border-radius-lg shadow-sm">


                </div>
            </div>
            <div class="col-auto my-auto">
                <div class="h-100">
                    <h5 class="mb-1">
                        {{logged_user.first_name}} {{logged_user.last_name}}
                    </h5>
                    <p class="mb-0 font-weight-bold text-sm">
                        {{logged_user.email}}
                    </p>
                </div>
            </div>

        </div>
    </div>
</div>
<!-- sección 2 cards -->
<div class="container-fluid py-4">
    <div class="row my-4">

        <!-- card izquierda -->
        <div class="col-lg-4 col-md-6 mb-md-0">
            <div class="card mb-2">
                <div class="card-header pb-0 p-3">
                    <h6 class="mb-1">Editar dirección</h6>

                </div>
                <div class=" col-md-12 d-flex flex-column">
                    <div class="card card-plain mt-1">
                        <div class="card-header pb-0 text-left bg-transparent">

                            {% if messages %}
                            <ul class="messages">
                                {% for message in messages%}
                                <li class="text-danger"><strong class="text-danger text-capitalize">{{message.tags}}:</strong> {{message}} {% endfor %}</li>
                            </ul>
                            {% else %}Por favor registre los campos a modificar{% endif %}
                            </p>
                        </div>

                        <div class="card-body">
                            <form role="form text-left" method="post" action="/user_dir/update/{{edit_dir.id}}">

                                {% csrf_token %}

                                <label for="nomdirec" class="form-label">Dirección </label>
                                <div class="mb-2">
                                    <input type="text" class="form-control" name="nomdirec" placeholder="Ingrese dirección completa" value="{{ edit_dir.nombre_dir }}" required>
                                </div>
                                <label for="celular" class="form-label">Teléfono</label>
                                <div class="mb-2">
                                    <input type="number" class="form-control" name="celular" placeholder="Ingrese número de teléfono" value="{{ edit_dir.celular }}" required>
                                </div>
                                <label for="desc" class="form-label">Referencia</label>
                                <div class="mb-2">
                                    <textarea class="form-control" name="desc" placeholder="Ingrese referencia" required>{{ edit_dir.desc }}</textarea>
                                </div>

                                <label for="id_lat" class="form-label">Latitud</label>
                                <div class="mb-2">
                                    <input type="text" class="form-control" name="id_lat" id="id_lat" placeholder="Ingrese coordenadas latitud" value="{{ edit_dir.lat }}" readonly>
                                </div>
                                <label for="id_lng" class="form-label">Longitud</label>
                                <div class="mb-2">
                                    <input type="text" class="form-control" name="id_lng" id="id_lng" placeholder="Ingrese coordenadas longitud" value="{{ edit_dir.long }}" readonly>
                                </div>

                                <div class="mb-3 row g-2 text-center">
                                    <div class="col-md">
                                        <button type="submit" name="save" class="btn bg-gradient-info mt-4 mb-0">Guardar</button>
                                    </div>
                                    <div class="col-md">
                                        <a href="/user/gest_direccion">
                                            <button type="button" class="btn bg-gradient-primary  mt-4 mb-0">Cancelar</button>
                                        </a>

                                    </div>
                                </div>

                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- card derecha -->
        <div class="col-lg-8 col-md-6">
            <div class="card mb-2">
                <div class="card-header pb-0 p-3">

                    <div class="col-lg-6 col-7">
                        <h6>Ubicación Mapa</h6>
                        <span> Si no Carga Google Maps clic </span>
                        <a title="Reload!" href="/user/gest_direccion" onclick="window.location.reload(true)">Aqui !</a>

                        <div id="mapa" class="capas "></div>
                        <script src="https://maps.googleapis.com/maps/api/js?key={{google_api_key}}&callback=initMap&libraries=&v=weekly" async></script>
                        <script src="/static/assets/js/google.js"></script>
                    </div>


                </div>
                <div class="card-body px-0 pb-2">

                </div>
            </div>

        </div>
    </div>


</div>


{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script src="https://maps.googleapis.com/maps/api/js?key={{google_api_key}}&callback=initMap&libraries=&v=weekly" async></script>
<script src="/static/assets/js/google.js"></script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>

{% endblock javascripts %}